In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [22]:
df = pd.read_csv('/home/jingo-green/Desktop/imax/data/dataset_phishing_trimmed.csv')
df.head()
X = df.drop(columns=['status'])
y = df['status']

In [23]:
X.head()

,length_url,length_hostname,ip,https_token,nb_subdomains,prefix_suffix,shortening_service,ratio_digits_url,phish_hints,nb_hyperlinks,domain_age,web_traffic,google_index,nb_specialchars,brand_flags,tld_subdomain_abnormal,nb_redirection_total,suspicious_html_score
0,37,19,0,1,3,0,0,0.000000,0,17,-1,0,1,7,0,0,0,1
1,77,23,1,1,1,0,0,0.220779,0,30,5767,0,1,7,0,0,1,1
2,126,50,1,0,3,1,0,0.150794,0,4,4004,5828815,1,19,0,1,1,1
3,18,11,0,1,2,0,0,0.000000,0,149,-1,107721,0,5,0,0,1,1
4,55,15,0,1,2,0,0,0.000000,0,102,8175,8725,0,10,0,0,1,1

In [24]:
y.head()

0    0
1    1
2    1
3    0
4    0
Name: status, dtype: int64

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=42, stratify=y)

In [26]:
X_train.head()

,length_url,length_hostname,ip,https_token,nb_subdomains,prefix_suffix,shortening_service,ratio_digits_url,phish_hints,nb_hyperlinks,domain_age,web_traffic,google_index,nb_specialchars,brand_flags,tld_subdomain_abnormal,nb_redirection_total,suspicious_html_score
7609,64,16,1,0,2,0,0,0.109375,0,86,7909,939,1,10,0,0,1,1
6408,128,50,1,0,3,1,0,0.187500,0,4,4003,5816617,1,19,0,1,1,1
7464,79,11,0,0,3,0,1,0.000000,2,0,-1,0,1,18,0,0,0,0
9286,99,16,0,1,2,0,0,0.111111,0,37,9318,13,1,20,1,0,1,1
5159,44,14,1,1,3,0,0,0.159091,0,71,7160,2336,1,9,0,0,2,1

In [27]:
X_test.head()

,length_url,length_hostname,ip,https_token,nb_subdomains,prefix_suffix,shortening_service,ratio_digits_url,phish_hints,nb_hyperlinks,domain_age,web_traffic,google_index,nb_specialchars,brand_flags,tld_subdomain_abnormal,nb_redirection_total,suspicious_html_score
6172,59,10,0,1,3,1,0,0.000000,2,0,-1,0,1,11,0,0,0,1
9810,118,38,1,1,2,1,0,0.194915,0,75,1279,0,1,11,0,1,0,1
8537,54,23,0,1,2,1,0,0.018519,0,75,135,0,1,9,0,0,0,2
605,39,22,0,0,1,0,0,0.000000,0,0,-1,0,1,6,0,0,0,2
6549,25,16,0,0,2,0,0,0.000000,0,47,6290,460823,0,6,0,0,0,1

In [28]:
y_train.head()

7609    0
6408    1
7464    1
9286    0
5159    0
Name: status, dtype: int64

In [29]:
y_test.head()

6172    1
9810    1
8537    1
605     1
6549    0
Name: status, dtype: int64

In [30]:
rf = RandomForestClassifier(random_state=42)

In [31]:
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [32]:
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1143
           1       0.94      0.96      0.95      1143

    accuracy                           0.95      2286
   macro avg       0.95      0.95      0.95      2286
weighted avg       0.95      0.95      0.95      2286

In [33]:
from datetime import datetime
samples = len(X_train)

for sub in range(5, 101, 5):
    start = datetime.now()
    subset = int(samples*(sub/100))
    subx = X_train.iloc[:subset] 
    suby = y_train.iloc[:subset]
    rfc = RandomForestClassifier(random_state=42)
    rfc.fit(subx, suby)
    y_pred = rfc.predict(X_test)
    end = datetime.now()
    print(f"duration={end-start}, subset={sub}%\n{classification_report(y_test, y_pred)}")

duration=0:00:00.108203, subset=5%
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      1143
           1       0.92      0.93      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.122740, subset=10%
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      1143
           1       0.93      0.92      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.146378, subset=15%
              precision    recall  f1-score   support

           0       0.93      0.92      0.92      1143
           1       0.92      0.93      0.92      1143

    accuracy                           0.92      2286
   macro avg       0.92      0.92      0.92      2286
weighted avg       0.92      0.92      0.92      2286

duration=0:00:00.169916, subset=20%
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      1143
           1       0.92      0.93      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.193145, subset=25%
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      1143
           1       0.93      0.93      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.214713, subset=30%
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      1143
           1       0.92      0.93      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.239258, subset=35%
              precision    recall  f1-score   support

           0       0.94      0.93      0.93      1143
           1       0.93      0.94      0.93      1143

    accuracy                           0.93      2286
   macro avg       0.93      0.93      0.93      2286
weighted avg       0.93      0.93      0.93      2286

duration=0:00:00.266220, subset=40%
              precision    recall  f1-score   support

           0       0.94      0.93      0.94      1143
           1       0.93      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.292737, subset=45%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.320728, subset=50%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.349662, subset=55%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.370423, subset=60%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.410643, subset=65%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.424960, subset=70%
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      1143
           1       0.94      0.94      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.459024, subset=75%
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      1143
           1       0.94      0.95      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.496377, subset=80%
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      1143
           1       0.94      0.95      0.94      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.504585, subset=85%
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      1143
           1       0.94      0.95      0.95      1143

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

duration=0:00:00.544071, subset=90%
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1143
           1       0.94      0.95      0.95      1143

    accuracy                           0.95      2286
   macro avg       0.95      0.95      0.95      2286
weighted avg       0.95      0.95      0.95      2286

duration=0:00:00.572328, subset=95%
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1143
           1       0.94      0.95      0.95      1143

    accuracy                           0.95      2286
   macro avg       0.95      0.95      0.95      2286
weighted avg       0.95      0.95      0.95      2286

duration=0:00:00.615781, subset=100%
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      1143
           1       0.94      0.96      0.95      1143

    accuracy                           0.95      2286
   macro avg       0.95      0.95      0.95      2286
weighted avg       0.95      0.95      0.95      2286

In [42]:
y_train

7609    0
6408    1
7464    1
9286    0
5159    0
       ..
8364    1
9876    1
4943    1
9054    1
8427    1
Name: status, Length: 9144, dtype: int64

In [43]:
X_train

,length_url,length_hostname,ip,https_token,nb_subdomains,prefix_suffix,shortening_service,ratio_digits_url,phish_hints,nb_hyperlinks,domain_age,web_traffic,google_index,nb_specialchars,brand_flags,tld_subdomain_abnormal,nb_redirection_total,suspicious_html_score
7609,64,16,1,0,2,0,0,0.109375,0,86,7909,939,1,10,0,0,1,1
6408,128,50,1,0,3,1,0,0.187500,0,4,4003,5816617,1,19,0,1,1,1
7464,79,11,0,0,3,0,1,0.000000,2,0,-1,0,1,18,0,0,0,0
9286,99,16,0,1,2,0,0,0.111111,0,37,9318,13,1,20,1,0,1,1
5159,44,14,1,1,3,0,0,0.159091,0,71,7160,2336,1,9,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,60,18,0,1,3,0,1,0.100000,0,64,7298,0,0,12,1,0,0,1
9876,36,18,0,1,3,0,0,0.027778,0,7,92,0,1,7,0,0,0,1
4943,36,29,0,1,2,0,1,0.000000,0,14,7295,0,1,5,1,0,1,1
9054,52,22,0,0,3,1,0,0.038462,1,4,13,0,1,10,0,0,1,1
8427,56,15,0,1,3,1,0,0.017857,2,0,8293,150166,1,11,0,0,0,2

In [44]:
s0 = X_train.to_dict(orient='records')
s1 = y_train.to_dict()

In [45]:
s0

[{'length_url': 64,
  'length_hostname': 16,
  'ip': 1,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.109375,
  'phish_hints': 0,
  'nb_hyperlinks': 86,
  'domain_age': 7909,
  'web_traffic': 939,
  'google_index': 1,
  'nb_specialchars': 10,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 128,
  'length_hostname': 50,
  'ip': 1,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.1875,
  'phish_hints': 0,
  'nb_hyperlinks': 4,
  'domain_age': 4003,
  'web_traffic': 5816617,
  'google_index': 1,
  'nb_specialchars': 19,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 79,
  'length_hostname': 11,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 1,
  'ratio_digits_url': 0.0,
  'phish_hints': 2,
  'nb_hyperlinks': 0,
  'domain_age': -1,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 18,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 0},
 {'length_url': 99,
  'length_hostname': 16,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.111111111,
  'phish_hints': 0,
  'nb_hyperlinks': 37,
  'domain_age': 9318,
  'web_traffic': 13,
  'google_index': 1,
  'nb_specialchars': 20,
  'brand_flags': 1,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 44,
  'length_hostname': 14,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.159090909,
  'phish_hints': 0,
  'nb_hyperlinks': 71,
  'domain_age': 7160,
  'web_traffic': 2336,
  'google_index': 1,
  'nb_specialchars': 9,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 2,
  'suspicious_html_score': 1},
 {'length_url': 56,
  'length_hostname': 16,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.25,
  'phish_hints': 0,
  'nb_hyperlinks': 0,
  'domain_age': 5803,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 10,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 109,
  'length_hostname': 20,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.201834862,
  'phish_hints': 3,
  'nb_hyperlinks': 1,
  'domain_age': 658,
  'web_traffic': 9558747,
  'google_index': 1,
  'nb_specialchars': 14,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 41,
  'length_hostname': 10,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 1,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 9,
  'domain_age': 3567,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 29,
  'length_hostname': 21,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.206896552,
  'phish_hints': 0,
  'nb_hyperlinks': 11,
  'domain_age': 257,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 7,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 27,
  'length_hostname': 15,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 26,
  'domain_age': -1,
  'web_traffic': 4090060,
  'google_index': 0,
  'nb_specialchars': 7,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 94,
  'length_hostname': 28,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.265957447,
  'phish_hints': 0,
  'nb_hyperlinks': 31,
  'domain_age': 1016,
  'web_traffic': 1211946,
  'google_index': 1,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 33,
  'length_hostname': 24,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 22,
  'domain_age': 2840,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 24,
  'length_hostname': 15,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.041666667,
  'phish_hints': 0,
  'nb_hyperlinks': 21,
  'domain_age': 2379,
  'web_traffic': 115241,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 0},
 {'length_url': 21,
  'length_hostname': 13,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 135,
  'domain_age': 6577,
  'web_traffic': 4902560,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 0},
 {'length_url': 243,
  'length_hostname': 12,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.106995885,
  'phish_hints': 0,
  'nb_hyperlinks': 503,
  'domain_age': 798,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 15,
  'brand_flags': 1,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 3,
  'suspicious_html_score': 2},
 {'length_url': 22,
  'length_hostname': 13,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 16,
  'domain_age': 805,
  'web_traffic': 45133,
  'google_index': 1,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 21,
  'length_hostname': 12,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 1,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 217,
  'domain_age': -1,
  'web_traffic': 828180,
  'google_index': 0,
  'nb_specialchars': 5,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 53,
  'length_hostname': 19,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.037735849,
  'phish_hints': 0,
  'nb_hyperlinks': 203,
  'domain_age': 6669,
  'web_traffic': 6844,
  'google_index': 1,
  'nb_specialchars': 9,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 2},
 {'length_url': 39,
  'length_hostname': 25,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 90,
  'domain_age': 959,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 7,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 47,
  'length_hostname': 17,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 3,
  'nb_hyperlinks': 11,
  'domain_age': 7378,
  'web_traffic': 746847,
  'google_index': 1,
  'nb_specialchars': 10,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 32,
  'length_hostname': 23,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 158,
  'domain_age': -1,
  'web_traffic': 1363440,
  'google_index': 0,
  'nb_specialchars': 7,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 35,
  'length_hostname': 23,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 1,
  'shortening_service': 1,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 26,
  'domain_age': -1,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 8,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 122,
  'length_hostname': 46,
  'ip': 1,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.172131148,
  'phish_hints': 0,
  'nb_hyperlinks': 51,
  'domain_age': 3993,
  'web_traffic': 5707171,
  'google_index': 1,
  'nb_specialchars': 19,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 24,
  'length_hostname': 17,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 1,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 0,
  'domain_age': -1,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 4,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 34,
  'length_hostname': 25,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 41,
  'domain_age': 7296,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 392,
  'length_hostname': 11,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.038265306,
  'phish_hints': 3,
  'nb_hyperlinks': 21,
  'domain_age': -1,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 90,
  'brand_flags': 1,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 2,
  'suspicious_html_score': 2},
 {'length_url': 50,
  'length_hostname': 14,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 51,
  'domain_age': 2305,
  'web_traffic': 541454,
  'google_index': 1,
  'nb_specialchars': 8,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 54,
  'length_hostname': 13,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.111111111,
  'phish_hints': 0,
  'nb_hyperlinks': 340,
  'domain_age': 8554,
  'web_traffic': 9753,
  'google_index': 0,
  'nb_specialchars': 10,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 52,
  'length_hostname': 16,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 2,
  'nb_hyperlinks': 1,
  'domain_age': 8346,
  'web_traffic': 1,
  'google_index': 0,
  'nb_specialchars': 9,
  'brand_flags': 1,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 0},
 {'length_url': 29,
  'length_hostname': 22,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 279,
  'domain_age': 6466,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 5,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 2},
 {'length_url': 38,
  'length_hostname': 15,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 28,
  'domain_age': 4309,
  'web_traffic': 630249,
  'google_index': 0,
  'nb_specialchars': 8,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 0},
 {'length_url': 39,
  'length_hostname': 25,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.205128205,
  'phish_hints': 0,
  'nb_hyperlinks': 8,
  'domain_age': 1338,
  'web_traffic': 22211,
  'google_index': 1,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 0,
  'suspicious_html_score': 0},
 {'length_url': 32,
  'length_hostname': 13,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.3125,
  'phish_hints': 0,
  'nb_hyperlinks': 53,
  'domain_age': -1,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 8,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 102,
  'length_hostname': 13,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 1,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.058823529,
  'phish_hints': 0,
  'nb_hyperlinks': 339,
  'domain_age': 3647,
  'web_traffic': 2175,
  'google_index': 0,
  'nb_specialchars': 17,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 18,
  'length_hostname': 11,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 1,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 105,
  'domain_age': -1,
  'web_traffic': 1111694,
  'google_index': 0,
  'nb_specialchars': 4,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 1},
 {'length_url': 58,
  'length_hostname': 40,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 1,
  'ratio_digits_url': 0.103448276,
  'phish_hints': 3,
  'nb_hyperlinks': 22,
  'domain_age': 5615,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 33,
  'length_hostname': 24,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 19,
  'domain_age': 1080,
  'web_traffic': 2016291,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 98,
  'length_hostname': 17,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 1,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 211,
  'domain_age': 1317,
  'web_traffic': 889963,
  'google_index': 1,
  'nb_specialchars': 14,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 2},
 {'length_url': 81,
  'length_hostname': 18,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.024691358,
  'phish_hints': 1,
  'nb_hyperlinks': 0,
  'domain_age': -1,
  'web_traffic': 43886,
  'google_index': 0,
  'nb_specialchars': 18,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 1,
  'suspicious_html_score': 3},
 {'length_url': 64,
  'length_hostname': 35,
  'ip': 1,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 1,
  'ratio_digits_url': 0.21875,
  'phish_hints': 0,
  'nb_hyperlinks': 21,
  'domain_age': 5627,
  'web_traffic': 0,
  'google_index': 1,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 49,
  'length_hostname': 30,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 1,
  'domain_age': 7083,
  'web_traffic': 17964,
  'google_index': 1,
  'nb_specialchars': 7,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 52,
  'length_hostname': 17,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 167,
  'domain_age': 8146,
  'web_traffic': 12421,
  'google_index': 0,
  'nb_specialchars': 10,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 0},
 {'length_url': 123,
  'length_hostname': 39,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.06504065,
  'phish_hints': 0,
  'nb_hyperlinks': 142,
  'domain_age': 7446,
  'web_traffic': 0,
  'google_index': 0,
  'nb_specialchars': 19,
  'brand_flags': 1,
  'tld_subdomain_abnormal': 1,
  'nb_redirection_total': 0,
  'suspicious_html_score': 1},
 {'length_url': 61,
  'length_hostname': 14,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 3,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.06557377,
  'phish_hints': 0,
  'nb_hyperlinks': 0,
  'domain_age': 7189,
  'web_traffic': 80480,
  'google_index': 0,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 3},
 {'length_url': 23,
  'length_hostname': 15,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 463,
  'domain_age': 3317,
  'web_traffic': 1009644,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 84,
  'length_hostname': 10,
  'ip': 1,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 1,
  'shortening_service': 0,
  'ratio_digits_url': 0.273809524,
  'phish_hints': 0,
  'nb_hyperlinks': 57,
  'domain_age': 3289,
  'web_traffic': 8181278,
  'google_index': 1,
  'nb_specialchars': 11,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 1,
  'suspicious_html_score': 2},
 {'length_url': 26,
  'length_hostname': 17,
  'ip': 0,
  'https_token': 0,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 0,
  'ratio_digits_url': 0.0,
  'phish_hints': 0,
  'nb_hyperlinks': 503,
  'domain_age': 5434,
  'web_traffic': 30291,
  'google_index': 0,
  'nb_specialchars': 6,
  'brand_flags': 0,
  'tld_subdomain_abnormal': 0,
  'nb_redirection_total': 0,
  'suspicious_html_score': 2},
 {'length_url': 29,
  'length_hostname': 22,
  'ip': 0,
  'https_token': 1,
  'nb_subdomains': 2,
  'prefix_suffix': 0,
  'shortening_service': 1,
  'ratio_digits_url': 0.068965517,

In [46]:
s1

{7609: 0,
 6408: 1,
 7464: 1,
 9286: 0,
 5159: 0,
 1669: 1,
 8601: 1,
 3499: 1,
 7380: 1,
 7812: 0,
 8794: 1,
 3204: 1,
 4166: 0,
 9108: 0,
 4838: 1,
 743: 1,
 5064: 0,
 6575: 0,
 7483: 1,
 2304: 1,
 9780: 0,
 599: 0,
 8766: 1,
 5826: 0,
 2890: 0,
 658: 1,
 5829: 1,
 900: 0,
 2273: 1,
 9896: 0,
 3783: 0,
 7029: 1,
 11319: 1,
 11073: 0,
 178: 0,
 952: 1,
 5472: 0,
 1710: 1,
 10999: 0,
 7890: 1,
 1039: 1,
 3320: 0,
 6998: 0,
 10121: 0,
 5504: 0,
 4770: 1,
 9145: 0,
 4110: 1,
 2903: 1,
 8881: 1,
 3126: 1,
 8691: 0,
 4461: 1,
 10850: 0,
 72: 0,
 9950: 1,
 594: 1,
 6541: 0,
 7194: 1,
 9107: 0,
 5128: 1,
 8649: 1,
 9929: 1,
 9328: 1,
 2251: 1,
 9040: 1,
 6067: 0,
 3490: 0,
 9458: 0,
 6830: 1,
 1739: 1,
 5653: 0,
 4225: 1,
 6642: 0,
 2000: 0,
 8243: 1,
 780: 1,
 1715: 0,
 5152: 0,
 6578: 0,
 9382: 1,
 6435: 0,
 1955: 0,
 2592: 1,
 8673: 1,
 671: 0,
 6289: 1,
 5386: 1,
 7725: 1,
 2888: 1,
 8311: 0,
 10401: 0,
 2899: 1,
 9344: 0,
 5061: 1,
 6839: 1,
 4502: 0,
 8564: 0,
 8830: 0,
 10897: 0,
 1692: 1,
 822: 1,
 7316: 0,
 1232: 1,
 7871: 0,
 9503: 1,
 5101: 1,
 3155: 1,
 3927: 0,
 1744: 0,
 7160: 1,
 967: 0,
 2194: 1,
 344: 0,
 4469: 1,
 6000: 1,
 2711: 1,
 6313: 1,
 4650: 0,
 6688: 0,
 11122: 1,
 2610: 1,
 730: 1,
 1657: 1,
 9833: 1,
 11372: 0,
 4800: 1,
 3195: 1,
 1507: 1,
 5691: 0,
 483: 1,
 8266: 0,
 4106: 0,
 10974: 0,
 9348: 1,
 2872: 0,
 750: 1,
 8907: 1,
 6171: 0,
 3109: 1,
 3915: 0,
 5751: 0,
 8639: 0,
 3705: 1,
 2914: 0,
 3069: 0,
 8215: 0,
 5846: 0,
 8697: 1,
 3666: 0,
 9720: 1,
 4095: 0,
 6796: 1,
 978: 0,
 4510: 1,
 1170: 1,
 439: 1,
 9619: 1,
 9972: 1,
 4278: 1,
 9004: 0,
 207: 1,
 3447: 0,
 8079: 1,
 4888: 0,
 2039: 0,
 372: 1,
 4940: 0,
 10029: 1,
 8092: 1,
 4401: 1,
 2033: 1,
 7811: 1,
 403: 1,
 9500: 1,
 4196: 0,
 8524: 1,
 3987: 0,
 3103: 1,
 6965: 0,
 7807: 0,
 719: 0,
 1137: 0,
 1605: 1,
 4996: 1,
 3531: 1,
 11399: 1,
 541: 0,
 3460: 1,
 9429: 0,
 11017: 0,
 1445: 0,
 1405: 1,
 11123: 1,
 7742: 1,
 9228: 1,
 10707: 0,
 4848: 0,
 3376: 0,
 653: 1,
 8928: 1,
 2040: 1,
 5588: 0,
 7439: 0,
 10512: 1,
 10340: 0,
 4950: 0,
 9136: 1,
 7344: 0,
 1559: 0,
 1091: 1,
 6286: 0,
 1086: 0,
 9191: 1,
 4282: 0,
 2582: 0,
 10022: 0,
 7705: 1,
 4941: 0,
 7232: 1,
 8268: 0,
 4109: 0,
 1938: 1,
 503: 0,
 210: 1,
 7404: 0,
 5401: 0,
 1060: 0,
 10192: 1,
 7300: 1,
 238: 0,
 6331: 0,
 9218: 0,
 5360: 1,
 10520: 0,
 6431: 1,
 1929: 1,
 3628: 0,
 10185: 1,
 8081: 1,
 8146: 0,
 10681: 1,
 9329: 0,
 4056: 1,
 7969: 0,
 6089: 1,
 4083: 0,
 4139: 0,
 9405: 0,
 5973: 1,
 2114: 0,
 96: 0,
 5238: 1,
 5979: 1,
 7568: 1,
 7700: 0,
 11403: 1,
 10580: 1,
 2430: 1,
 9873: 0,
 10551: 0,
 8300: 1,
 10752: 0,
 368: 1,
 9742: 0,
 7447: 1,
 728: 1,
 7927: 0,
 318: 0,
 6279: 1,
 59: 1,
 3027: 0,
 8004: 1,
 1515: 1,
 10496: 0,
 3178: 0,
 7955: 1,
 1376: 0,
 2783: 0,
 8581: 1,
 1811: 0,
 6229: 1,
 10549: 0,
 1894: 0,
 4230: 0,
 9670: 1,
 2754: 0,
 4811: 1,
 7516: 0,
 4755: 0,
 8681: 0,
 7857: 0,
 8046: 0,
 2806: 1,
 686: 0,
 10670: 1,
 10173: 0,
 4425: 1,
 5585: 0,
 2687: 1,
 124: 1,
 1438: 1,
 6949: 0,
 1904: 1,
 5703: 0,
 5693: 0,
 6663: 0,
 3740: 0,
 10415: 0,
 2067: 1,
 8168: 0,
 1632: 1,
 1461: 0,
 4963: 0,
 1572: 0,
 4444: 1,
 8826: 1,
 8334: 0,
 2015: 0,
 2644: 0,
 7634: 1,
 10544: 0,
 8308: 0,
 2848: 1,
 9115: 1,
 7327: 1,
 1415: 1,
 3521: 0,
 1708: 0,
 4563: 0,
 4449: 0,
 792: 0,
 8958: 1,
 4742: 0,
 6385: 0,
 5663: 0,
 10077: 1,
 348: 0,
 4181: 0,
 4188: 0,
 4057: 0,
 2675: 1,
 1119: 0,
 6316: 0,
 8493: 1,
 7051: 0,
 10574: 0,
 3039: 1,
 387: 1,
 1193: 1,
 3430: 1,
 11018: 1,
 350: 0,
 1068: 1,
 10818: 0,
 697: 1,
 10959: 0,
 6882: 1,
 3801: 1,
 8294: 1,
 3887: 0,
 8301: 0,
 9282: 1,
 6425: 1,
 8833: 0,
 2403: 0,
 5066: 1,
 841: 0,
 1831: 0,
 4798: 1,
 620: 0,
 10350: 1,
 148: 1,
 3508: 1,
 10605: 1,
 4445: 0,
 7365: 0,
 4731: 0,
 10099: 1,
 5609: 0,
 3863: 1,
 6438: 0,
 8320: 0,
 8785: 1,
 1640: 0,
 5211: 1,
 20: 0,
 8696: 1,
 4373: 1,
 1093: 0,
 7381: 0,
 8497: 0,
 6215: 1,
 10245: 1,
 677: 1,
 5042: 0,
 8755: 0,
 8986: 0,
 3745: 1,
 4248: 1,
 8792: 1,
 4516: 0,
 11347: 1,
 6395: 1,
 10652: 0,
 4701: 1,
 7640: 1,
 5666: 1,
 1579: 0,
 9708: 1,
 5510: 0,
 5228: 1,
 8226: 0,
 9789: 1,
 5249: 1,
 8970: 1,
 9497: 0,
 11034: 1,
 7268: 0,
 8455: 1,
 8112: 1,
 9020: 0,
 8246: 1,
 1434: 1,
 3911: 1,
 3655: 1,
 1682: 0,
 7917: 0,
 1191: 1,
 1265: 1,
 4428: 1,
 4610: 1,
 4090: 1,
 6040: 0,
 5428: 1,
 37: 0,
 6763: 0,
 1274: 1,
 10242: 1,
 4361: 1,
 9518: 1,
 4872: 0,
 4078: 1,
 5631: 1,
 4960: 1,
 1356: 1,
 8609: 0,
 8806: 0,
 4623: 1,
 9717: 0,
 29: 1,
 5149: 1,
 10841: 1,
 8031: 0,
 10320: 0,
 8603: 1,
 10577: 0,
 4726: 1,
 782: 0,
 6675: 0,
 10909: 1,
 624: 0,
 7256: 0,
 4507: 0,
 9239: 0,
 6083: 0,
 6325: 1,
 4331: 0,
 1326: 1,
 6456: 1,
 7847: 0,
 2254: 1,
 6346: 0,
 5704: 0,
 3571: 1,
 10241: 1,
 4405: 0,
 763: 0,
 8461: 0,
 4597: 0,
 5758: 1,
 5052: 0,
 10065: 0,
 2884: 1,
 7719: 1,
 3245: 1,
 707: 0,
 7152: 0,
 5750: 1,
 7978: 0,
 7726: 1,
 9363: 0,
 1592: 1,
 7688: 1,
 7596: 0,
 4458: 1,
 6343: 0,
 10233: 1,
 2875: 1,
 7711: 0,
 7322: 0,
 7074: 1,
 2858: 1,
 5584: 0,
 290: 0,
 3473: 0,
 2201: 1,
 8593: 1,
 6614: 0,
 7637: 1,
 10345: 1,
 5031: 1,
 6231: 0,
 4604: 0,
 3362: 0,
 962: 1,
 2932: 0,
 10919: 1,
 9119: 1,
 5695: 1,
 8165: 1,
 5043: 0,
 1366: 1,
 7522: 1,
 9067: 0,
 3076: 1,
 1018: 1,
 3659: 1,
 7851: 0,
 3061: 0,
 5291: 0,
 856: 0,
 10813: 0,
 9884: 0,
 6383: 1,
 6768: 0,
 4988: 1,
 259: 0,
 6274: 1,
 815: 1,
 943: 0,
 10483: 0,
 10325: 0,
 718: 0,
 8228: 0,
 9850: 0,
 992: 1,
 10015: 0,
 10399: 0,
 8602: 0,
 5996: 0,
 6641: 0,
 6059: 0,
 7155: 0,
 3416: 1,
 4911: 0,
 3272: 0,
 7866: 1,
 2338: 0,
 853: 1,
 8445: 0,
 5847: 0,
 7120: 0,
 8809: 0,
 6128: 1,
 3865: 1,
 10706: 0,
 10856: 0,
 7041: 0,
 4933: 1,
 6412: 1,
 5842: 1,
 4017: 1,
 4290: 0,
 4244: 1,
 8823: 1,
 1202: 1,
 828: 1,
 6523: 0,
 8094: 0,
 6442: 1,
 7390: 0,
 3326: 0,
 4807: 0,
 4525: 0,
 4985: 0,
 668: 1,
 2016: 1,
 7501: 1,
 7652: 1,
 8132: 1,
 3837: 0,
 4064: 0,
 6239: 0,
 7226: 1,
 3315: 0,
 8177: 1,
 717: 1,
 3388: 0,
 3727: 0,
 237: 1,
 2956: 0,
 4129: 0,
 1155: 0,
 4379: 1,
 9498: 0,
 6148: 1,
 1271: 0,
 4574: 1,
 1442: 0,
 2327: 1,
 1493: 0,
 3094: 0,
 5894: 0,
 7846: 1,
 980: 1,
 8270: 1,
 5941: 0,
 8808: 1,
 1455: 1,
 417: 1,
 8375: 1,
 6268: 1,
 4762: 1,
 3334: 0,
 10150: 0,
 7366: 1,
 1627: 1,
 1361: 0,
 7407: 0,
 4377: 1,
 8514: 1,
 769: 1,
 8431: 0,
 6460: 1,
 330: 0,
 2068: 1,
 11376: 0,
 468: 1,
 2977: 0,
 1867: 1,
 6733: 1,
 4158: 0,
 4194: 0,
 1776: 1,
 1652: 1,
 8731: 0,
 10827: 0,
 11279: 1,
 7159: 0,
 7819: 0,
 4335: 1,
 2958: 0,
 9473: 0,
 2256: 1,
 2486: 1,
 6422: 1,
 6510: 1,
 1997: 0,
 6133: 1,
 7900: 0,
 2584: 0,
 6832: 0,
 5193: 1,
 3485: 1,
 6197: 0,
 9690: 1,
 10434: 0,
 7460: 0,
 6762: 1,
 2489: 1,
 8801: 0,
 5578: 1,
 1688: 1,
 9541: 1,
 4766: 0,
 7219: 0,
 7691: 0,
 8500: 1,
 7542: 0,
 3458: 0,
 8993: 1,
 3233: 1,
 4515: 1,
 9432: 0,
 673: 0,
 10491: 1,
 11296: 1,
 10190: 1,
 5389: 1,
 2789: 1,
 9618: 1,
 5963: 1,
 6350: 0,
 3014: 1,
 4112: 1,
 1772: 0,
 9583: 0,
 9442: 1,
 6100: 1,
 975: 1,
 6370: 0,
 3484: 1,
 6565: 1,
 5019: 1,
 3886: 1,
 714: 1,
 2641: 1,
 6564: 0,
 1595: 0,
 1371: 0,
 4588: 0,
 2776: 0,
 8380: 1,
 6310: 1,
 539: 1,
 10087: 1,
 8700: 0,
 2150: 0,
 11068: 0,
 9143: 0,
 9895: 1,
 5901: 0,
 2389: 1,
 3211: 1,
 8747: 1,
 10214: 1,
 3664: 1,
 1174: 1,
 2157: 1,
 6253: 0,
 6015: 0,
 11297: 1,
 7004: 0,
 10002: 0,
 329: 1,
 7382: 0,
 1933: 0,
 6500: 0,
 8175: 1,
 8879: 0,
 1027: 1,
 2257: 0,
 5191: 1,
 2658: 1,
 7674: 0,
 269: 0,
 3196: 1,
 7641: 0,
 5927: 1,
 1985: 0,
 7451: 0,
 10116: 1,
 10769: 1,
 4408: 1,
 4276: 0,
 4035: 0,
 6604: 0,
 1481: 1,
 3063: 1,
 6087: 0,
 4840: 0,
 1706: 1,
 9058: 0,
 219: 1,
 9014: 1,
 3779: 0,
 7975: 0,
 182: 1,
 4085: 1,
 5877: 1,
 2401: 0,
 140: 1,
 4348: 1,
 3477: 0,
 2387: 1,
 80: 1,
 4714: 1,
 7930: 0,
 6581: 1,
 6834: 0,
 411: 1,
 7089: 1,
 8501: 1,
 3615: 0,
 3283: 0,
 5324: 1,
 4645: 0,
 7364: 1,
 6799: 0,
 679: 0,
 10092: 0,
 5452: 0,
 9781: 1,
 11427: 0,
 5825: 1,
 4899: 1,
 10872: 0,
 4877: 0,
 9514: 1,
 9758: 1,
 6620: 1,
 10899: 1,
 8241: 0,
 10168: 1,
 1065: 1,
 4593: 1,
 5805: 1,
 3185: 1,
 4321: 1,
 8027: 0,
 9548: 0,
 91: 1,
 8171: 1,
 11355: 0,
 7: 1,
 3132: 1,
 11191: 0,
 7384: 0,
 9362: 0,
 5536: 0,
 887: 1,
 10610: 1,
 1568: 1,
 2232: 0,
 10227: 0,
 161: 0,
 2743: 1,
 6717: 0,
 11336: 1,
 1301: 0,
 8199: 1,
 3519: 0,
 5460: 1,
 1573: 1,
 2411: 0,
 6342: 0,
 6734: 1,
 2970: 0,
 409: 0,
 7971: 1,
 5914: 1,
 4481: 0,
 9689: 0,
 1347: 1,
 9665: 0,
 9650: 0,
 4794: 1,
 6322: 1,
 9624: 0,
 2247: 1,
 8388: 1,
 676: 0,
 10056: 1,
 700: 1,
 4189: 0,
 2331: 1,
 2537: 0,
 10503: 0,
 5308: 1,
 4744: 1,
 10418: 0,
 1365: 1,
 6139: 1,
 5201: 0,
 1856: 1,
 7385: 0,
 9652: 0,
 251: 1,
 5158: 0,
 9922: 0,
 2999: 1,
 4782: 1,
 10158: 0,
 4590: 1,
 6697: 0,
 1874: 0,
 6737: 1,
 10951: 1,
 434: 0,
 829: 0,
 4806: 0,
 10755: 0,
 9975: 1,
 4824: 0,
 11042: 1,
 1663: 0,
 7699: 0,
 4938: 1,
 5900: 1,
 4247: 1,
 3497: 1,
 1504: 0,
 2376: 0,
 598: 1,
 2174: 1,
 4252: 0,
 5808: 0,
 3006: 0,
 10386: 1,
 578: 0,
 10968: 0,
 4961: 1,
 3830: 1,
 5058: 0,
 11228: 0,
 4881: 0,
 10727: 0,
 11266: 1,
 8131: 0,
 7702: 0,
 5168: 0,
 702: 1,
 2236: 0,
 3187: 1,
 10735: 0,
 3074: 1,
 9140: 0,
 8061: 0,
 5346: 1,
 3896: 0,
 4508: 0,
 7653: 0,
 8104: 0,
 6822: 0,
 8379: 1,
 2836: 1,
 2787: 1,
 10272: 0,
 2092: 0,
 4471: 1,
 5098: 0,
 7339: 1,
 366: 0,
 5204: 0,
 10347: 1,
 1278: 0,
 4264: 0,
 5230: 0,
 5698: 1,
 664: 1,
 4350: 0,
 3081: 1,
 6980: 0,
 44: 0,
 4079: 0,
 8077: 1,
 11136: 1,
 6960: 1,
 9642: 0,
 8157: 0,
 2345: 1,
 6617: 0,
 4421: 1,
 8605: 1,
 8333: 0,
 3647: 0,
 10547: 1,
 4018: 1,
 1539: 1,
 1199: 1,
 3573: 1,
 8395: 1,
 8926: 0,
 5097: 0,
 7236: 1,
 6991: 0,
 9059: 0,
 10815: 0,
 2775: 0,
 7416: 0,
 8653: 1,
 10651: 0,
 9649: 1,
 2763: 1,
 6872: 1,
 2638: 1,
 8234: 0,
 5684: 0,
 821: 1,
 10471: 0,
 5445: 1,
 1456: 1,
 2105: 0,
 58: 1,
 6034: 1,
 9277: 0,
 3921: 0,
 9381: 1,
 4839: 0,
 8931: 1,
 246: 1,
 6605: 0,
 3631: 1,
 3620: 0,
 5549: 0,
 7149: 1,
 8873: 1,
 7823: 1,
 5241: 1,
 ...}

In [47]:
s2 = pd.DataFrame.from_dict(s0)
s3 = pd.Series(s1)

In [48]:
s2

,length_url,length_hostname,ip,https_token,nb_subdomains,prefix_suffix,shortening_service,ratio_digits_url,phish_hints,nb_hyperlinks,domain_age,web_traffic,google_index,nb_specialchars,brand_flags,tld_subdomain_abnormal,nb_redirection_total,suspicious_html_score
0,64,16,1,0,2,0,0,0.109375,0,86,7909,939,1,10,0,0,1,1
1,128,50,1,0,3,1,0,0.187500,0,4,4003,5816617,1,19,0,1,1,1
2,79,11,0,0,3,0,1,0.000000,2,0,-1,0,1,18,0,0,0,0
3,99,16,0,1,2,0,0,0.111111,0,37,9318,13,1,20,1,0,1,1
4,44,14,1,1,3,0,0,0.159091,0,71,7160,2336,1,9,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9139,60,18,0,1,3,0,1,0.100000,0,64,7298,0,0,12,1,0,0,1
9140,36,18,0,1,3,0,0,0.027778,0,7,92,0,1,7,0,0,0,1
9141,36,29,0,1,2,0,1,0.000000,0,14,7295,0,1,5,1,0,1,1
9142,52,22,0,0,3,1,0,0.038462,1,4,13,0,1,10,0,0,1,1
9143,56,15,0,1,3,1,0,0.017857,2,0,8293,150166,1,11,0,0,0,2

In [49]:
s3

7609    0
6408    1
7464    1
9286    0
5159    0
       ..
8364    1
9876    1
4943    1
9054    1
8427    1
Length: 9144, dtype: int64